services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: "postgres://postgres:postgres@db:5432/tutor_app_back?sslmode=disable"
    networks:
      - tutor_app_back_network
    restart: unless-stopped
    depends_on:
      - db
      - pgadmin

  db:
    container_name: db
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tutor_app_back
      POSTGRES_HOST: db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - tutor_app_back_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tutor_app_back_network
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:

networks:
  tutor_app_back_network:
    driver: bridge