// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package users

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// UpdateUserInfo defines model for UpdateUserInfo.
type UpdateUserInfo struct {
	Bio       string `json:"bio"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Location  string `json:"location"`
	Phone     string `json:"phone"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Avatar     *string              `json:"avatar,omitempty"`
	Bio        *string              `json:"bio,omitempty"`
	CreatedAt  *time.Time           `json:"created_at,omitempty"`
	Email      *openapi_types.Email `json:"email,omitempty"`
	FirstName  *string              `json:"first_name,omitempty"`
	Id         *openapi_types.UUID  `json:"id,omitempty"`
	IsVerified *bool                `json:"is_verified,omitempty"`
	LastName   *string              `json:"last_name,omitempty"`
	Location   *string              `json:"location,omitempty"`
	Phone      *string              `json:"phone,omitempty"`
	Role       *string              `json:"role,omitempty"`
	UpdatedAt  *time.Time           `json:"updated_at,omitempty"`
}

// PatchUsersProfileIdJSONRequestBody defines body for PatchUsersProfileId for application/json ContentType.
type PatchUsersProfileIdJSONRequestBody = UpdateUserInfo

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get user profile
	// (GET /users/profile/{id})
	GetUsersProfileId(ctx echo.Context, id openapi_types.UUID) error
	// Update user profile
	// (PATCH /users/profile/{id})
	PatchUsersProfileId(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetUsersProfileId converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersProfileId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersProfileId(ctx, id)
	return err
}

// PatchUsersProfileId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchUsersProfileId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchUsersProfileId(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/users/profile/:id", wrapper.GetUsersProfileId)
	router.PATCH(baseURL+"/users/profile/:id", wrapper.PatchUsersProfileId)

}

type GetUsersProfileIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetUsersProfileIdResponseObject interface {
	VisitGetUsersProfileIdResponse(w http.ResponseWriter) error
}

type GetUsersProfileId200JSONResponse UserProfile

func (response GetUsersProfileId200JSONResponse) VisitGetUsersProfileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersProfileId401JSONResponse struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response GetUsersProfileId401JSONResponse) VisitGetUsersProfileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersProfileId500JSONResponse struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response GetUsersProfileId500JSONResponse) VisitGetUsersProfileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchUsersProfileIdRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PatchUsersProfileIdJSONRequestBody
}

type PatchUsersProfileIdResponseObject interface {
	VisitPatchUsersProfileIdResponse(w http.ResponseWriter) error
}

type PatchUsersProfileId200JSONResponse struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response PatchUsersProfileId200JSONResponse) VisitPatchUsersProfileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchUsersProfileId400JSONResponse struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response PatchUsersProfileId400JSONResponse) VisitPatchUsersProfileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchUsersProfileId500JSONResponse struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response PatchUsersProfileId500JSONResponse) VisitPatchUsersProfileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get user profile
	// (GET /users/profile/{id})
	GetUsersProfileId(ctx context.Context, request GetUsersProfileIdRequestObject) (GetUsersProfileIdResponseObject, error)
	// Update user profile
	// (PATCH /users/profile/{id})
	PatchUsersProfileId(ctx context.Context, request PatchUsersProfileIdRequestObject) (PatchUsersProfileIdResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetUsersProfileId operation middleware
func (sh *strictHandler) GetUsersProfileId(ctx echo.Context, id openapi_types.UUID) error {
	var request GetUsersProfileIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersProfileId(ctx.Request().Context(), request.(GetUsersProfileIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersProfileId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUsersProfileIdResponseObject); ok {
		return validResponse.VisitGetUsersProfileIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchUsersProfileId operation middleware
func (sh *strictHandler) PatchUsersProfileId(ctx echo.Context, id openapi_types.UUID) error {
	var request PatchUsersProfileIdRequestObject

	request.Id = id

	var body PatchUsersProfileIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchUsersProfileId(ctx.Request().Context(), request.(PatchUsersProfileIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchUsersProfileId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchUsersProfileIdResponseObject); ok {
		return validResponse.VisitPatchUsersProfileIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
